version: "3.8"

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Amadou_dev301030"
      MYSQL_DATABASE: "TestProjetJava"
      MYSQL_USER: "amadou-dev"
      MYSQL_PASSWORD: "Amadou_dev301030"

