version: "3.8"

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "user_password"
      MYSQL_DATABASE: "gestion_entreprise"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user_password"

